-- 학생이름과 주소지를 표시하시오. 단, 출력 헤더는 "학생 이름" , "주소지"로 하고, 정렬은
-- 이름으로 오름차순 표시하도록 한다.
SELECT STUDENT_NAME "학생 이름" ,STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 1;

-- 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순으로 화면에 출력하시오.
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

-- 주소지가 강원도나 경기도인 학생들 중 1900 년대 학번을 가진 학생들의 이름과 학번, 주소를
-- 이름의 오름차순으로 화면에 출력하시오. 단, 출력헤더에는 "학생이름", "학번", "거주지 주소"
-- 가 출력되도록 한다.
SELECT STUDENT_NAME,STUDENT_NO,STUDENT_ADDRESS
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%')
AND STUDENT_NO NOT LIKE 'A%'
ORDER BY 1;

-- 현재 법학과 교수 중 가장 나이가 많은 사람부터 이름을 확인할 수 있는 SQL 문장을 작성하시오
-- (법학과의 '학과코드'는 학과 테이블을 조회해서 찾아내도록 하자)
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY 2;

-- 2004년 2학기에 'C3118100' 과목을 수강한 학생들의 학점을 조회하려고 한다. 학점이 높은 
-- 학생부터 표시하고 , 학점이 같으면 학번이 낮은 학생부터 표시하는 구문을 작성해보시오.
SELECT * FROM TB_GRADE;

SELECT STUDENT_NO,TO_CHAR(POINT, '9.00')
FROM TB_GRADE
WHERE TERM_NO = '200402'
AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC;

-- 학생 번호, 학생 이름, 학과 이름을 학생 이름으로 오름차순 정렬하여 출력하는 SQL문을
-- 작성 하시오
SELECT STUDENT_NO, STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2;

-- 춘 기술대학교의 과목 이름과 과목의 학과이름을 출력하는 SQL 문장을 작성하시오.
SELECT CLASS_NAME,DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-- 과목별 교수 이름을 찾으려고 한다. 과목 이름과 교수 이름을 출력하는 SQL 문을 작성하시오
-- TB_CLASS_PROFESSOR : 과목별 교수의 정보를 저장한 테이블 (과목 코드, 학과 코드)

SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);

-- 오라클
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS C , TB_CLASS_PROFESSOR B , TB_PROFESSOR A
WHERE C.CLASS_NO = B.CLASS_NO
AND B.PROFESSOR_NO = A.PROFESSOR_NO;


-- TB_CLASS와 TB_PROFESSOR 테이블이 공통으로
-- DEPARTMENT_NO 칼럼을 가지고 있다 해서 이를 이용해서 JOIN을 하면 안됨!
/*
TB_CLASS와 TB_PROFESSOR 테이블을 조회 해보면 
같은 칼럼 값을 가지는 DEPARTMENT_NO가 많이 존재함
--> 이럴 경우 
    TB_CLASS의 DEPARTMNET_NO 와
    TB_PRODESSOR 의 DEPARMENT_NO 칼럼 값들이
    서로 연결되기 위한 모든 경우의 수를 만들어냄 (곱집합이 되어버림)
    
*/


-- 8번의 결과 중 '인문사회' 계열에 속한 과목의 교수 이름을 찾으려고 한다. 이에 해당하는 
-- 과목 이름과 교수 이름을 출력하는 SQL문을 작성하시오

SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT  USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
WHERE CATEGORY = '인문사회';  -- 된다 !!!!!!

SELECT CLASS_NAME, PROFESSOR_NAME FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO) 
JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)  
WHERE CATEGORY = '인문사회';

-- 오라클
SELECT CLASS_NAME,PROFESSOR_NAME 
FROM TB_CLASS C , TB_CLASS_PROFESSOR CP , TB_PROFESSOR P  , TB_DEPARTMENT D
WHERE C.CLASS_NO = CP.CLASS_NO
AND CP.PROFESSOR_NO = P.PROFESSOR_NO
AND P.DEPARTMENT_NO = D.DEPARTMENT_NO
AND CATEGORY = '인문사회';


-- '음악학과' 학생들의 평점을 구하려고 한다. 음악학과 학생들의 "학번" ,"학생 이름" , "전체
-- "평점을 구하는 SQL 문장을 작성하시오. (단 평점은 소수점 1자리 까지만 반올림하여 표시한다.)

SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", 
ROUND(AVG(POINT), 1) "전체 평점" FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO) 
WHERE DEPARTMENT_NAME = '음악학과' 
GROUP BY STUDENT_NO, STUDENT_NAME 
ORDER BY STUDENT_NO;