--ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CREATE USER do_not_sick_js IDENTIFIED BY donot1234;

--ALTER USER do_not_sick_js DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

--GRANT CONNECT, RESOURCE, CREATE VIEW TO do_not_sick_js;

--grant create any job to do_not_sick_js; -- 프로시저 사용하려면 사용자명에 자기꺼 넣기

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "MEMBER_ID"   VARCHAR2(50)      NOT NULL,
   "MEMBER_PW"   VARCHAR2(100)      NOT NULL,
   "MEMBER_NM"   VARCHAR2(30)      NOT NULL,
   "MEMBER_PNO"   VARCHAR2(30)      NOT NULL,
   "MEMBER_TEL"   VARCHAR2(30)      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50)      NOT NULL,
   "MEMBER_ADD"   VARCHAR2(4000)      NOT NULL,
   "SECESSION_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MEMBER_ADMIN"   CHAR(1)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_PNO" IS '주민등록번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADD" IS '주소';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴Y''회원N';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADMIN" IS '관리자Y''회원N';



CREATE TABLE "RESERVATION" (
   "BOOK_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "CHECKIN_DT"   DATE      NOT NULL,
   "CHECKOUT_DT"   DATE      NOT NULL,
   "BOOK_PERSON"   NUMBER   DEFAULT 0   NOT NULL,
   "CHECK_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "ROOM_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "RESERVATION"."BOOK_NO" IS '예약번호(시퀀스)';

COMMENT ON COLUMN "RESERVATION"."CHECKIN_DT" IS '체크인 날짜';

COMMENT ON COLUMN "RESERVATION"."CHECKOUT_DT" IS '체크아웃 날짜';

COMMENT ON COLUMN "RESERVATION"."BOOK_PERSON" IS '인원';

COMMENT ON COLUMN "RESERVATION"."CHECK_FL" IS '체크인 여부';

COMMENT ON COLUMN "RESERVATION"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "RESERVATION"."ROOM_NO" IS '객실 번호(시퀀스)';


CREATE TABLE "ROOM" (
   "ROOM_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "ROOM_NM"   VARCHAR2(30)      NOT NULL,
   "ROOM_PRICE"   NUMBER      NOT NULL,
   "ROOM_IMG"   VARCHAR2(4000)      NOT NULL,
   "ROOM_INFO"   VARCHAR2(4000)      NOT NULL,
   "ROOM_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "HOTEL_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "ROOM"."ROOM_NO" IS '객실 번호(시퀀스)';

COMMENT ON COLUMN "ROOM"."ROOM_NM" IS '객실명';

COMMENT ON COLUMN "ROOM"."ROOM_PRICE" IS '객실 가격';

COMMENT ON COLUMN "ROOM"."ROOM_IMG" IS '객실 사진';

COMMENT ON COLUMN "ROOM"."ROOM_INFO" IS '객실 소개';

COMMENT ON COLUMN "ROOM"."ROOM_FL" IS '객실 예약 여부';

COMMENT ON COLUMN "ROOM"."HOTEL_NO" IS '호텔번호';



CREATE TABLE "BOARD" (
   "BOARD_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "BOARD_TITLE"   VARCHAR2(300)      NULL,
   "BOARD_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "BOARD_DT"   DATE   DEFAULT SYSDATE   NOT NULL,
   "BOARD_ST"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "BOARD_CD"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "REVIEW_STAR"   NUMBER       NULL,
   "BOOK_NO" NUMBER NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호(시퀀스)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글내용';

COMMENT ON COLUMN "BOARD"."BOARD_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글상태(정상N,삭제Y)';

COMMENT ON COLUMN "BOARD"."BOARD_CD" IS '게시판 코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOARD"."REVIEW_STAR" IS '별점';



CREATE TABLE "BOARD_TYPE" (
   "BOARD_CD"   NUMBER   PRIMARY KEY   NOT NULL,
   "BOARD_NM"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CD" IS '게시판 코드';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NM" IS '게시판 이름';


CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER	PRIMARY KEY	NOT NULL,
	"EVENT_TITLE"	VARCHAR2(1000)		NOT NULL,
	"EVENT_CONTENT"	VARCHAR2(4000)		NULL,
	"EVENT_DT"	DATE	NOT NULL,
   	"EVENT_ST" CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "EVENT"."EVENT_NO" IS '이벤트 번호 (시퀀스)';

COMMENT ON COLUMN "EVENT"."EVENT_TITLE" IS '이벤트 제목';

COMMENT ON COLUMN "EVENT"."EVENT_CONTENT" IS '이벤트 내용';

COMMENT ON COLUMN "EVENT"."EVENT_DT" IS '이벤트 종료일';

COMMENT ON COLUMN "EVENT"."EVENT_ST" IS '삭제Y 정상 N';

CREATE TABLE "EVENT_FL" (
   "BINGO_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "UPDOWN_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "EVENT_FL"."BINGO_FL" IS '빙고참여여부';

COMMENT ON COLUMN "EVENT_FL"."UPDOWN_FL" IS '업다운참여여부';

COMMENT ON COLUMN "EVENT_FL"."MEMBER_NO" IS '회원번호';


CREATE TABLE "REPLY" (
   "REPLY_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "REPLY_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "CREATE_DT"   DATE   DEFAULT SYSDATE   NOT NULL,
   "REPLY_ST"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호(시퀀스)';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "REPLY"."CREATE_DT" IS '댓글 작성일';

COMMENT ON COLUMN "REPLY"."REPLY_ST" IS '댓글 상태';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글번호(시퀀스)';


CREATE TABLE "LIKELIST" (
   "ROOM_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "LIKELIST"."ROOM_NO" IS '객실 번호(시퀀스)';

COMMENT ON COLUMN "LIKELIST"."MEMBER_NO" IS '회원번호';



CREATE TABLE "CALCULATE" (
   "CALCULATE_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "CALCULATE_WAY"   VARCHAR2(30)      NOT NULL,
   "CALCULATE_ST"   CHAR(1)   DEFAULT 'N'   CHECK(CALCULATE_ST IN ('N','I','Y','F')),
   "CALCULATE_PRICE"   NUMBER      NOT NULL,
   "ACCOUNT_NUMBER"   VARCHAR2(100)      NOT NULL,
   "BOOK_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CALCULATE"."CALCULATE_NO" IS '결제번호';

COMMENT ON COLUMN "CALCULATE"."CALCULATE_WAY" IS '결제수단';

COMMENT ON COLUMN "CALCULATE"."CALCULATE_ST" IS '결제여부';

COMMENT ON COLUMN "CALCULATE"."CALCULATE_PRICE" IS '결제금액';

COMMENT ON COLUMN "CALCULATE"."ACCOUNT_NUMBER" IS '입금계좌';

COMMENT ON COLUMN "CALCULATE"."BOOK_NO" IS '예약번호(시퀀스)';



CREATE TABLE "REVIEW_IMG" (
   "IMG_REVIEW_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "IMG_REVIEW_RENAME"   VARCHAR2(4000)      NOT NULL,
   "IMG_REVIEW_LEVEL"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "REVIEW_IMG"."IMG_REVIEW_NO" IS '이미지 번호';

COMMENT ON COLUMN "REVIEW_IMG"."IMG_REVIEW_RENAME" IS '이미지 저장 경로+ 변경명';

COMMENT ON COLUMN "REVIEW_IMG"."IMG_REVIEW_LEVEL" IS '이미지 위치 지정 번호';

COMMENT ON COLUMN "REVIEW_IMG"."BOARD_NO" IS '게시글번호(시퀀스)';



CREATE TABLE "EVENT_IMG" (
   "IMG_EVENT_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "IMG_EVENT_RENAME"   VARCHAR2(4000)      NOT NULL,
   "IMG_EVENT_LEVEL"   NUMBER      NOT NULL,
   "EVENT_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "EVENT_IMG"."IMG_EVENT_NO" IS '이미지 번호';

COMMENT ON COLUMN "EVENT_IMG"."IMG_EVENT_RENAME" IS '이미지 저장 경로+ 변경명';

COMMENT ON COLUMN "EVENT_IMG"."IMG_EVENT_LEVEL" IS '이미지 위치 지정 번호';

COMMENT ON COLUMN "EVENT_IMG"."EVENT_NO" IS '이벤트 번호 (시퀀스)';


CREATE TABLE "COUPON" (
   "COUPON_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "COUPON_NM"   VARCHAR2(100)      DEFAULT '30000원 할인 쿠폰',
   "COUPON_SALE"   NUMBER   DEFAULT 30000   NOT NULL,
   "COUPON_DT"   DATE   DEFAULT '2023-12-31'   NOT NULL,
   "COUPON_ST"   CHAR(1)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "COUPON"."COUPON_NO" IS '쿠폰 번호';

COMMENT ON COLUMN "COUPON"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COUPON"."COUPON_NM" IS '쿠폰명';

COMMENT ON COLUMN "COUPON"."COUPON_SALE" IS '할인금액';

COMMENT ON COLUMN "COUPON"."COUPON_DT" IS '유효기간';

COMMENT ON COLUMN "COUPON"."COUPON_ST" IS '사용Y''사용안함N';

CREATE TABLE "HOTEL" (
   "HOTEL_NO"   NUMBER   PRIMARY KEY   NOT NULL,
   "HOTEL_TITLE"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "HOTEL"."HOTEL_NO" IS '호텔번호';

COMMENT ON COLUMN "HOTEL"."HOTEL_TITLE" IS '호텔 지점';



CREATE TABLE "TAG" (
   "TAG_CONTENT"   VARCHAR2(4000)      NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "TAG_ST"   CHAR(1)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "TAG"."TAG_CONTENT" IS '태그내용';

COMMENT ON COLUMN "TAG"."BOARD_NO" IS '게시글번호(시퀀스)';

COMMENT ON COLUMN "TAG"."TAG_ST" IS '태그 상태';




CREATE TABLE "REPORT" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "REPORT_CONTENT"   VARCHAR2(4000)  NULL,
   "REPORT_ST"  CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "REPORT"."BOARD_NO" IS '게시글번호(시퀀스)';

COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고내용';

COMMENT ON COLUMN "REPORT"."REPORT_ST" IS '신고처리현황';

-- 시퀀스

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원 번호 시퀀스

CREATE SEQUENCE SEQ_BOOK_NO NOCACHE; -- 예약 번호 시퀀스

CREATE SEQUENCE SEQ_ROOM_NO NOCACHE; -- 객실 번호 시퀀스

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시길 번호 시퀀스

CREATE SEQUENCE SEQ_BOARD_CD NOCACHE; -- 게시판 코드 시퀀스

CREATE SEQUENCE SEQ_EVENT_NO NOCACHE; -- 이벤트 번호 시퀀스

CREATE SEQUENCE SEQ_REPLY_NO NOCACHE; -- 댓글 번호 시퀀스

CREATE SEQUENCE SEQ_CALCULATE_NO NOCACHE; -- 결제 번호 시퀀스

CREATE SEQUENCE SEQ_IMG_REVIEW_NO NOCACHE; -- 댓글 이미지 번호 시퀀스

CREATE SEQUENCE SEQ_IMG_EVENT_NO NOCACHE; -- 이벤트 이미지 번호 시퀀스

CREATE SEQUENCE SEQ_COUPON_NO NOCACHE; -- 쿠폰 번호 시퀀스

CREATE SEQUENCE SEQ_HOTEL_NO NOCACHE; -- 호텔 번호 시퀀스




ALTER TABLE RESERVATION
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER"; -- 예약 테이블에 멤버 번호 참조

ALTER TABLE RESERVATION
ADD FOREIGN KEY("ROOM_NO")
REFERENCES "ROOM";  -- 예약 테이블에 객실 번호 참조

ALTER TABLE ROOM
ADD FOREIGN KEY("HOTEL_NO")
REFERENCES "HOTEL";  -- 객실 테이블에 호텔 번호 참조

ALTER TABLE BOARD
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER";   -- 게시글 테이블에 멤버 번호 참조

ALTER TABLE BOARD
ADD FOREIGN KEY("BOARD_CD")
REFERENCES "BOARD_TYPE";   -- 게시글 테이블에 게시글 코드 참조

ALTER TABLE REPLY
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER"; -- 댓글 테이블에 멤버 번호 참조

ALTER TABLE REPLY
ADD FOREIGN KEY("BOARD_NO")
REFERENCES "BOARD"; -- 댓글 테이블에 게시글 번호 참조

ALTER TABLE LIKELIST
ADD FOREIGN KEY("ROOM_NO")
REFERENCES "ROOM"; -- 찜목록 테이블에 객실 번호 참조

ALTER TABLE LIKELIST
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER"; -- 찜목록 테이블에 멤버 번호 참조

ALTER TABLE CALCULATE
ADD FOREIGN KEY("BOOK_NO")
REFERENCES "RESERVATION"; -- 찜 목록에 예약 번호 참조

ALTER TABLE REVIEW_IMG
ADD FOREIGN KEY("BOARD_NO")
REFERENCES "BOARD"; -- 리뷰 이미지 테이블에 게시글 번호 참조

ALTER TABLE EVENT_IMG
ADD FOREIGN KEY("EVENT_NO")
REFERENCES "EVENT"; -- 이벤트 이미지 테이블에 이벤트 번호 참조

ALTER TABLE COUPON
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER"; -- 쿠폰 테이블에 멤버 번호 참조

ALTER TABLE TAG
ADD FOREIGN KEY("BOARD_NO")
REFERENCES "BOARD"; -- 태그 테이블에 게시글 번호 참조

ALTER TABLE REPORT
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER"; -- 신고 테이블에 회원 번호 참조


ALTER TABLE REPORT
ADD FOREIGN KEY("BOARD_NO")
REFERENCES "BOARD"; -- 신고 테이블에 회원 번호 참조

ALTER TABLE EVENT_FL
ADD FOREIGN KEY("MEMBER_NO")
REFERENCES "MEMBER";  -- 이벤트 테이블에 멤버 번호 참조

ALTER TABLE BOARD
ADD FOREIGN KEY("BOOK_NO")
REFERENCES "RESERVATION"; -- 게시판 테이블에 예약 번호 참조

BEGIN
   DBMS_SCHEDULER.CREATE_JOB (
      job_name        => 'UPDATE_FL_JOB',
      job_type        => 'PLSQL_BLOCK',
      job_action      => 'BEGIN 
                            UPDATE EVENT_FL 
                            SET UPDOWN_FL = ''N'',
                                BINGO_FL = ''N''; 
                            COMMIT; 
                         END;',
      start_date      => SYSTIMESTAMP,
      repeat_interval => 'FREQ=DAILY; INTERVAL=1', -- 매일 1회 실행
      enabled         => TRUE
   );
END;
/

-- 유저 더미 데이터
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'admin01','aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==','관리자','970521-1346782','01012345678','admin@naver.com','04651,,서울특별시,,주소는몰라요',DEFAULT,'Y');
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user01','aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==','유저일','970521-1346782','01012345678','user01@naver.com','04651,,서울특별시1,,주소는몰라요1',DEFAULT,DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user02','aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==','유저이','970521-2315464','01012345678','user02@naver.com','04651,,서울특별시2,,주소는몰라요2',DEFAULT,DEFAULT);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user03','aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg==','유저삼','970521-1231454','01012345678','user03@naver.com','04651,,서울특별시3,,주소는몰라요3',DEFAULT,DEFAULT);
-- 비밀번호 pass01! -> 암호화한거임


-- 게시글 종류
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'공지사항');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'질문게시판');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'리뷰게시판');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'FAQ');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'관리자회원정보관리');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'관리자리뷰신고목록');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'관리자예약관리');
INSERT INTO BOARD_TYPE VALUES(SEQ_BOARD_CD.NEXTVAL,'관리자결제관리');


-- 게시글 더미 데이터
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,' [공지] 코로나19 감염병 관련 안내','신라스테이는 코로나19의 확산 방지를 위하여 14일이 경과하지 않은 해외 입국자, 자가격리 대상자, 방역당국 및 기업, 기관 등으로부터 코로나19 진단검사 대상으로 통보 또는 권유 받은 수검자, 유증상자의 투숙 및 호텔 시설 이용을 제한하오니 양해와 협조 부탁드립니다.<br><br>사전 승인을 받은 격리예외자는 입국 시 음성으로 판정된 경우에 한하여 호텔 이용이 가능합니다. <br><br>신라스테이는 시설 전체에 대한 정기적인 방역소독, 직원들에 대한 보건용품 지급과 위생 교육 강화 등 고객과 직원의 건강과 안전을 위해  최선을 다하고 있으며 <br>상황이 종식될 때까지 더욱 노력하겠습니다. 감사합니다.',DEFAULT,DEFAULT,1,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'[공지] 롯데호텔 개인정보처리방침 개정안내','항상 롯데호텔을 이용해 주시는 고객님께 감사드립니다.<br>개인정보처리방침이 개정되어 안내드립니다.<br><br>1. 개정사항<br>1) 개인정보 수집 부분 내용 추가<br>2) 개인정보 수집 부분 내용 수정<br>3) 개인정보 수집 부분 내용 추가<br>4) 개인정보 제공 및 위탁 내용 추가<br><br>2. 개정시기 : 2023년 8월 8일<br>공고시기 : 2022년 8월 4일',DEFAULT,DEFAULT,1,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'[공지]청소 로봇 운영 안내','K-호텔은 쾌적한 객실 층 복도 환경 조정을 위해 인공지능 건식 청소 로봇을 다음과 같이 운영하고 있으니, 이용에 참고 부탁드립니다.<br><br>- 시행 일자 : 2023년 8월 7일부<br>- 운영 시간 : 12:00 ~ 15:00<br><br>* 추가 문의사항은 롯데호텔 서울 객실관리팀(02-759-7361~2)로 연락 부탁 드립니다.',DEFAULT,DEFAULT,1,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'[공지]일회용품 사용 줄이기 ''Re:think'' 캠페인','롯데호텔앤리조트는 아름다운 자연과 소중한 환경을 보호하기 위해 노력하고 있습니다.<br><br>‘Re:think’ 캠페인의 일환으로 일회용품 사용 줄이기에 동참하고자 칫솔, 치약, 면도기, 쉐이빙 젤은 제공되지 않습니다.<br><br>고객님의 따뜻한 배려가 소중한 환경을 보호합니다.<br><br>시행 일시 : 2023년 8월 06일부.',DEFAULT,DEFAULT,1,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'[공지]시스템 점검 안내','항상 K-호텔을 애용해주시는 고객님께 감사 드립니다.<br><br>보다 안정화된 서비스를 제공해 드리기 위해 시스템 점검작업이 진행될 예정입니다.<br><br>작업시간 동안 K-호텔 공식 홈페이지 및 리워즈 APP 사용이 제한됩니다.<br><br>이용에 불편을 드려 대단히 죄송하다는 말씀 드리며, 고객님의 많은 양해 부탁드립니다..',DEFAULT,DEFAULT,1,1,NULL,NULL);



-- FAQ 더미 데이터
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'K-호텔 홈페이지 온라인 회원 가입은 어떻게 하나요?','화면 우측 상단의 Join 메뉴를 클릭하시면 회원 가입을 하실 수 있습니다.<br><br>더 플라자 홈페이지 회원 가입은 19세 이상의 성인만 가능합니다.',DEFAULT,DEFAULT,4,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'K-호텔 홈페이지 개인 정보 수정은 어떻게 하나요?','화면 우측 상단의 로그인 메뉴를 클릭하여 로그인 하신 후,<br>마이페이지 회원정보확인 화면에서 개인 정보 수정 버튼을 클릭하여 수정 하실 수 있습니다.',DEFAULT,DEFAULT,4,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'호텔 객실 내에서 인터넷 사용이 가능합니까?','K-호텔의 전 객실 내에서 유선, 무선 인터넷 사용이 무료로 이용 가능 합니다.',DEFAULT,DEFAULT,4,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'체크인과 체크아웃 시간은 언제입니까?','체크인 시간은 15:00이며, 체크아웃 시간은 12:00입니다.<br><br>문의 : 프론트 데스크 02-310-7700 ',DEFAULT,DEFAULT,4,1,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'호텔에 두고 온 분실물은 어떻게 찾습니까?','저희 K-호텔은 고객 유실물과 관련하여 <br>대한민국 민법 제 253조(유실물의 소유권취득)에 따라<br>고객유실물 관리 규정을 제정하여 운영하고 있습니다.',DEFAULT,DEFAULT,4,1,NULL,NULL);

-- Q/A 더미 데이터
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'객실에 구급약이 있나요?','저희 아이가 몸이 허약해서 잘 다치는데 객실에 구급약이 있는지 궁금하네요ㅠ',DEFAULT,DEFAULT,2,2,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'애완동물을 데리고 입실','애완 동물 데리고 입실 가능한가요? 저희 강아지는 배변도 정해진 곳에 잘해서 괜찮은데.....',DEFAULT,DEFAULT,2,3,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'객실 또는 호텔 내부에서 흡연할 곳이 있나요?','헤비 흡연러라....ㅎㅎ 흡연 장소좀 알려주세요 !!',DEFAULT,DEFAULT,2,4,NULL,NULL);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'레이트 체크아웃 금액','체크아웃 늦게하면 얼마 내야 해요 ?',DEFAULT,DEFAULT,2,3,NULL,NULL);

-- 댓글 더미 데이터 (Q/A 댓글)
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL,'저희 K-호텔 전 객실, 슬림/캡슐/카페에는 복도에 소화기함에 구급약품이 준비되어 있습니다. <br> 사용후 다음 응급 고객님을 위해 제자리에 보관해주세요. <br><br>단, 해열제, 진통제, 감기약과 같은 복용약의 경우 구비되어 있지 않습니다.',DEFAULT,DEFAULT,1,11);
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL,'저희 아이도 매번 아파서 호텔 갈때마다 물어보는데 항상 K-호텔은 준비가 되있어서 좋아요 ♥♥',DEFAULT,DEFAULT,2,11);
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL,'저희 K-호텔은 애왕동물과의 동반 입실이 불가능합니다.<br><br>이용에 불편을 드려 대단히 죄송하다는 말씀 드리며, 고객님의 많은 양해 부탁드립니다.. ',DEFAULT,DEFAULT,1,12);
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL,'저희 K-호텔은 전 객실 포함 건물 전체가 흡연금지 구역입니다. <br><br> 흡연은 건물 외부에서만 가능합니다.<br><br> 객실내에서 흡연하시는 경우 객실청소비용 30만원이 부과됩니다.',DEFAULT,DEFAULT,1,13);
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL,'저희 K-호텔은 퇴실 시간 이후에는 시간당 20,000원의 추가 요금이 발생합니다. <br><br> 14시 이후부터는 1박 요금이 부과됩니다.',DEFAULT,DEFAULT,1,14);
INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL,'저흰 호텔이 너무 편해서 잠을 더 자버린 결과....<br> 6만원 내버렸네요...ㅎ 그래도 다음 이용에 할인 받을 수 있는 쿠폰 받아서 또 가려구요!!ㅋㅋ',DEFAULT,DEFAULT,4,14);

-- 리뷰 더미 데이터
--INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'리뷰 더미 데이터 1','리뷰 더미 데이터 1번 입니다. ㅋㅋ',DEFAULT,DEFAULT,3,2,1,1);
--INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'리뷰 더미 데이터 2','리뷰 더미 데이터 2번 입니다. ㅎㅎ',DEFAULT,DEFAULT,3,3,2,2);
--INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'리뷰 더미 데이터 3','리뷰 더미 데이터 3번 입니다. ^^',DEFAULT,DEFAULT,3,4,3,3);
--INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'리뷰 더미 데이터 4','리뷰 더미 데이터 4번 입니다.bb',DEFAULT,DEFAULT,3,4,4,4);
--INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'리뷰 더미 데이터 5','리뷰 더미 데이터 5번 입니다. ㅜㅜ',DEFAULT,DEFAULT,3,3,5,5);
--INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL,'리뷰 더미 데이터 5','리뷰 더미 데이터 6번 입니다. ㅜㅜ',DEFAULT,DEFAULT,3,2,NULL,6);

-- 태그 더미 데이터
--INSERT INTO TAG VALUES('깨끗해요',16,DEFAULT);
--INSERT INTO TAG VALUES('아이와 가기 좋아요',17,DEFAULT);
--INSERT INTO TAG VALUES('조용해서 쉬기 좋아요',18,DEFAULT);
--INSERT INTO TAG VALUES('침구가 고급스러워요',19,DEFAULT);
--INSERT INTO TAG VALUES('애인과 가기 좋아요',20,DEFAULT);
--INSERT INTO TAG VALUES('파티하기 좋아요',21,DEFAULT);

-- 호텔 더미 데이터 
INSERT INTO HOTEL VALUES(SEQ_HOTEL_NO.NEXTVAL,'GANGNAM');
INSERT INTO HOTEL VALUES(SEQ_HOTEL_NO.NEXTVAL,'JONGRO');
INSERT INTO HOTEL VALUES(SEQ_HOTEL_NO.NEXTVAL,'DANGSAN');

-- 객실 더미 데이터 
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'DELUXE','400000','/resources/images/Deluxe-Room_1.jpg','강남점 디럭스룸 소개글','N',1);
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'STANDARD','600000','/resources/images/standard-Room_1.jpg','강남점 스탠다드룸 소개글','N',1);
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'SUITE','800000','/resources/images/suite-Room_1.jpg','강남점 스위트룸 소개글','N',1);

INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'DELUXE','400000','/resources/images/Deluxe-Room_JongRo_1.jpg','종로점 디럭스룸 소개글','N',2);
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'STANDARD','600000','/resources/images/standard-Room_JongRo_2.jpg','종로점 스탠다드룸 소개글','N',2);
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'SUITE','800000','/resources/images/suite-Room_JongRo_2.jpg','종로점 스위트룸 소개글','N',2);

INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'DELUXE','400000','/resources/images/Deluxe-Room_DangSan_3.jpg','당산점 디럭스룸 소개글','N',3);
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'STANDARD','600000','/resources/images/standard-Room_DangSan_3.jpg','당산점 스탠다드룸 소개글','N',3);
INSERT INTO ROOM VALUES(SEQ_ROOM_NO.NEXTVAL,'SUITE','800000','/resources/images/suite-Room_DangSan_3.jpg','당산점 스위트룸 소개글','N',3);


-- 예약 더미 데이터 
INSERT INTO RESERVATION VALUES(SEQ_BOOK_NO.NEXTVAL,'2023-04-08','2023-04-10',3,'Y',3,9);
INSERT INTO RESERVATION VALUES(SEQ_BOOK_NO.NEXTVAL,'2023-05-14','2023-06-20',2,'Y',2,5);
INSERT INTO RESERVATION VALUES(SEQ_BOOK_NO.NEXTVAL,'2023-06-19','2023-06-20',4,'Y',4,1);
INSERT INTO RESERVATION VALUES(SEQ_BOOK_NO.NEXTVAL,'2023-07-20','2023-07-21',4,'Y',3,8);
INSERT INTO RESERVATION VALUES(SEQ_BOOK_NO.NEXTVAL,'2023-07-21','2023-07-23',2,'Y',2,4);
INSERT INTO RESERVATION VALUES(SEQ_BOOK_NO.NEXTVAL,'2023-07-25','2023-07-29',2,'Y',4,2);

-- 결제 더미 데이터 
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',3);
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',5);
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',6);
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',7);
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',8);
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',9);
--INSERT INTO CALCULATE VALUES(SEQ_CALCULATE_NO.NEXTVAL,'무통장입금',DEFAULT,'400000','1000-2161-4567',10);

--쿠폰 더미 데이터
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,2,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,2,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,2,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,2,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,3,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,3,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,3,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);
--INSERT INTO COUPON VALUES(SEQ_COUPON_NO.NEXTVAL,3,'30000만원 할인 쿠폰',30000,DEFAULT,DEFAULT);

-- 이벤트 더미 데이터 
INSERT INTO EVENT VALUES(SEQ_EVENT_NO.NEXTVAL,'이벤트1','이벤트 1 내용입니다','2023-08-24 20:39:18',DEFAULT);

-- 찜목록 더미 데이터
--INSERT INTO LIKELIST VALUES(1,2);
--INSERT INTO LIKELIST VALUES(2,2);
--INSERT INTO LIKELIST VALUES(3,2);
--INSERT INTO LIKELIST VALUES(4,3);
--INSERT INTO LIKELIST VALUES(5,3);
--INSERT INTO LIKELIST VALUES(6,3);

-- 회원가입 시 자동으로 INSERT되는 EVENT_FL 데이터
INSERT INTO EVENT_FL VALUES(DEFAULT, DEFAULT,1);
INSERT INTO EVENT_FL VALUES(DEFAULT, DEFAULT,2);
INSERT INTO EVENT_FL VALUES(DEFAULT, DEFAULT,3);
INSERT INTO EVENT_FL VALUES(DEFAULT, DEFAULT,4);

-- 종료된 이벤트 더미데이터
INSERT INTO EVENT VALUES(SEQ_EVENT_NO.NEXTVAL,'종료이벤트1','이벤트 1 내용입니다','2021-08-24 20:39:18', DEFAULT); 
INSERT INTO EVENT_IMG VALUES(SEQ_IMG_EVENT_NO.NEXTVAL, '/resources/images/리뷰1.png', 0, SEQ_EVENT_NO.CURRVAL);


COMMIT;
